### ISSUE TITLE
ws链接报错

### ISSUE THREAD

**Issue by XM12G** [Tian-que/nonebot-adapter-kaiheila#10]
Error while process data from websocketwss://ws.kaiheila.cn/gateway?compress=0&token=别看！. Trying to reconnect...
Traceback (most recent call last):
  File "E:\Users\ji233\PycharmProjects\CuteProject\CuteRobot\bot.py", line 13, in <module>
    nonebot.run()
  File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\drivers\_block_driver.py", line 60, in run
    loop.run_until_complete(self.serve())
  File "C:\Users\ji233\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ji233\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\ji233\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ji233\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ji233\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\adapters\kaiheila\adapter.py", line 218, in _forward_ws
    event = self.json_to_event(json_data, bot and bot.self_id)
  File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\adapters\kaiheila\adapter.py", line 334, in json_to_event
    if json_data["d"]["author_id"] == self_id:
KeyError: 'author_id'

**Comment by Tian-que** [comment]
>if json_data["d"]["author_id"] == self_id:
这一块应当使用get，预计明天修复后重新发一个包

**Comment by Tian-que** [comment]
已重新出包
