### ISSUE TITLE
bot实际上应该可以发送image/video/file类型的消息

### ISSUE THREAD

**Issue by XM12G** [Tian-que/nonebot-adapter-kaiheila#12]
0.5版本更新后MessageSegment又发不出了

**Comment by XM12G** [comment]
试了一下，文字确实可以，图片不行
08-02 13:32:15 [ERROR] nonebot | Running matcher <Matcher from cuterobot.plugins.kook_memes, type=message, priority=12, temp=False> failed.
Traceback (most recent call last):
  File "E:\Users\ji233\PycharmProjects\CuteProject\CuteRobot\bot.py", line 13, in <module>
    nonebot.run()
  File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\drivers\_block_driver.py", line 60, in run
    loop.run_until_complete(self.serve())
  File "C:\Users\ji233\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\ji233\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\ji233\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\ji233\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\ji233\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
  File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "E:\Users\ji233\PycharmProjects\CuteProject\CuteRobot\cuterobot\plugins\kook_memes\__init__.py", line 47, in handle
    await matcher.finish(MessageSegment.image(t))
  File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\internal\matcher.py", line 464, in finish
    await cls.send(message, **kwargs)
  File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\internal\matcher.py", line 449, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\adapters\kaiheila\bot.py", line 210, in send
    return await self.__class__.send_handler(self, event, message, reply_sender, is_temp_msg, **kwargs)
  File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\adapters\kaiheila\bot.py", line 121, in send
    return await bot.send_msg(**params)
  File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\adapters\kaiheila\bot.py", line 295, in send_msg
    params["type"], params["content"] = await MessageSerializer(Message(message)).serialize()
  File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\adapters\kaiheila\message.py", line 241, in serialize
    raise UnsupportedMessageType()
nonebot.adapters.kaiheila.exception.UnsupportedMessageType

**Comment by ssttkkl** [comment]
Bot侧发送只支持"text", "kmarkdown", "card"三种类型。目前需要先调用bot.upload_file(file)上传文件，通过把返回的url以kmarkdown形式发送。


发件人: 宵暮十二宫 ***@***.***>
答复: Tian-que/nonebot-adapter-kaiheila ***@***.***>
日期: 2022年8月2日 星期二 13:32
收件人: Tian-que/nonebot-adapter-kaiheila ***@***.***>
抄送: ssttkkl ***@***.***>, Comment ***@***.***>
主题: Re: [Tian-que/nonebot-adapter-kaiheila] MessageSegment无法正常序列化 (Issue #12)


试了一下，文字确实可以，图片不行
08-02 13:32:15 [ERROR] nonebot | Running matcher <Matcher from cuterobot.plugins.kook_memes, type=message, priority=12, temp=False> failed.
Traceback (most recent call last):
File "E:\Users\ji233\PycharmProjects\CuteProject\CuteRobot\bot.py", line 13, in
nonebot.run()
File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot_init_.py", line 261, in run
get_driver().run(*args, **kwargs)
File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\drivers_block_driver.py", line 60, in run
loop.run_until_complete(self.serve())
File "C:\Users\ji233\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
self.run_forever()
File "C:\Users\ji233\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
super().run_forever()
File "C:\Users\ji233\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
self._run_once()
File "C:\Users\ji233\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
handle._run()
File "C:\Users\ji233\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
self._context.run(self._callback, *self._args)
File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)

File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\message.py", line 196, in run_matcher
await matcher.run(bot, event, state, stack, dependency_cache)
File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
await self.simple_run(bot, event, state, stack, dependency_cache)
File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
await handler(
File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\dependencies_init.py", line 92, in call
return await self.call(**values)
File "E:\Users\ji233\PycharmProjects\CuteProject\CuteRobot\cuterobot\plugins\kook_memes_init_.py", line 47, in handle
await matcher.finish(MessageSegment.image(t))
File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\internal\matcher.py", line 464, in finish
await cls.send(message, **kwargs)
File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\internal\matcher.py", line 449, in send
return await bot.send(event=event, message=_message, **kwargs)
File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\adapters\kaiheila\bot.py", line 210, in send
return await self.class.send_handler(self, event, message, reply_sender, is_temp_msg, **kwargs)
File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\adapters\kaiheila\bot.py", line 121, in send
return await bot.send_msg(**params)
File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\adapters\kaiheila\bot.py", line 295, in send_msg
params["type"], params["content"] = await MessageSerializer(Message(message)).serialize()
File "E:\Users\ji233\PycharmProjects\CuteProject\venv\lib\site-packages\nonebot\adapters\kaiheila\message.py", line 241, in serialize
raise UnsupportedMessageType()
nonebot.adapters.kaiheila.exception.UnsupportedMessageType

**Comment by ssttkkl** [comment]
将来版本考虑支持直接发送Image类型的消息

**Comment by XM12G** [comment]
事实上把and not for_send 删掉就可以了

**Comment by XM12G** [comment]
#13

**Comment by XM12G** [comment]
![image](https://user-images.githubusercontent.com/35884945/182299852-93c25013-efff-407e-bbf0-b2300fa0e28c.png)

**Comment by ssttkkl** [comment]
草，等我回家看看，API文档说的是只支持"text", "kmarkdown", "card"
另外"audio", "video", "file"你测试过了吗

**Comment by XM12G** [comment]
稍等
我逐一测试

**Comment by ssttkkl** [comment]
经过测试，image\file\video都可以上传，只有audio发送时提示无权限
![QQ截图20220802223726](https://user-images.githubusercontent.com/17331698/182401446-c97a28ea-249b-4791-8d2d-de372a173c8c.png)
![QQ截图20220802223735](https://user-images.githubusercontent.com/17331698/182401496-7f05cdd0-0ee2-4c68-8fd9-c774125a8bd7.png)
![QQ截图20220802223756](https://user-images.githubusercontent.com/17331698/182401500-a9633020-4945-41cb-9ae1-8fa694da8ab5.png)
![QQ截图20220802223822](https://user-images.githubusercontent.com/17331698/182401530-32c01317-412f-44bd-ba0d-94e0516ad0a5.png)
