### ISSUE TITLE
Call_Api

### ISSUE THREAD

**Issue by BuDingOwO** [Tian-que/nonebot-adapter-kaiheila#15]
Call_api的时候，返回
nonebot.adapters.kaiheila.exception.NetworkError: <NetWorkError message=HTTP request received unexpected status code: 400 ({'name': 'Bad Request', 'status': 400})>

完整Log

Traceback (most recent call last):
  File "C:\Users\ConBl\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ConBl\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ConBl\AppData\Local\Programs\Python\Python310\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\ConBl\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\ConBl\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\ConBl\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ConBl\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\ConBl\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\ConBl\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\ConBl\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\handlers\deploy.py", line 23, in run_bot
    nonebot.run()
  File "C:\Users\ConBl\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\ConBl\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\_block_driver.py", line 60, in run
    loop.run_until_complete(self.serve())
  File "C:\Users\ConBl\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\ConBl\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\ConBl\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\ConBl\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\ConBl\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\ConBl\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\ConBl\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\ConBl\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\ConBl\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
  File "C:\Users\ConBl\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "D:\Desktop\Bot\Dr407-Kook\.\src\plugins\Permission-Group-Manager\__init__.py", line 19, in Default_permission_Add_Handle
    result = await bot.call_api(api="guild-role/list", query={"guild_id": "00000000"})
  File "C:\Users\ConBl\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\kaiheila\bot.py", line 168, in call_api
    return await super().call_api(api, **data)
  File "C:\Users\ConBl\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\adapter\bot.py", line 117, in call_api
    raise exception
  File "C:\Users\ConBl\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\adapter\bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\ConBl\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\kaiheila\adapter.py", line 127, in _call_api
    raise NetworkError(
nonebot.adapters.kaiheila.exception.NetworkError: <NetWorkError message=HTTP request received unexpected status code: 400 ({'name': 'Bad Request', 'status': 400})>

代码段:

result = await bot.call_api(api="guild-role/list", query={"guild_id": "000000000"})

**Comment by ssttkkl** [comment]
已于0.1.0版本修复，现在参数不正确时抛出的是ActionFailed异常，并附带相关信息
