### ISSUE TITLE
call_api函数貌似有问题

### ISSUE THREAD

**Issue by HOursH** [Tian-que/nonebot-adapter-kaiheila#65]
传入数组无效
https://developer.kookapp.cn/doc/http/channel#语音频道之间移动用户

await KookBot.call_api(main_inst_bot, 'channel/move-user', target_id='频道ID', user_ids=['用户ID', '用户ID'])
报错：
Traceback (most recent call last):
  File "C:\Users\666\Desktop\666\main.py", line 578, in <module>
    nonebot.run()
  File "M:\python3.11\Lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "M:\python3.11\Lib\site-packages\nonebot\drivers\none.py", line 56, in run
    loop.run_until_complete(self._serve())
  File "M:\python3.11\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "M:\python3.11\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "M:\python3.11\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "M:\python3.11\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "M:\python3.11\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "M:\python3.11\Lib\site-packages\nonebot\message.py", line 466, in check_and_run_matcher
    if not await _check_matcher(
> File "M:\python3.11\Lib\site-packages\nonebot\message.py", line 371, in _check_matcher
    if not await Matcher.check_rule(bot, event, state, stack, dependency_cache):
  File "M:\python3.11\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 401, in check_rule
    return event_type == (cls.type or event_type) and await cls.rule(
  File "M:\python3.11\Lib\site-packages\nonebot\internal\rule.py", line 75, in __call__
    results = await asyncio.gather(
  File "M:\python3.11\Lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\666\Desktop\666\main.py", line 520, in handle_notice_QQ
    await KookBot.call_api(main_inst_bot, 'channel/move-user', target_id='频道ID', user_ids=['用户ID', '用户ID'])
  File "M:\python3.11\Lib\site-packages\nonebot\adapters\kaiheila\bot.py", line 204, in call_api
    return await super().call_api(api, **data)
  File "M:\python3.11\Lib\site-packages\nonebot\internal\adapter\bot.py", line 122, in call_api
    raise exception
  File "M:\python3.11\Lib\site-packages\nonebot\internal\adapter\bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "M:\python3.11\Lib\site-packages\nonebot\adapters\kaiheila\adapter.py", line 135, in _call_api
    return await self._do_call_api(api, data, bot.token)
  File "M:\python3.11\Lib\site-packages\nonebot\adapters\kaiheila\adapter.py", line 188, in _do_call_api
    raise e
  File "M:\python3.11\Lib\site-packages\nonebot\adapters\kaiheila\adapter.py", line 185, in _do_call_api
    result = _handle_api_result(resp)
  File "M:\python3.11\Lib\site-packages\nonebot\adapters\kaiheila\utils.py", line 79, in _handle_api_result
    raise ActionFailed(response)
nonebot.adapters.kaiheila.exception.ActionFailed: <ActionFailed: 200, code=40000, message=User Ids是无效的。, data={}>

**Comment by HOursH** [comment]
没事了，改成：
data = {
                'user_ids[]': team_1_user_ids,
                'target_id': team_1_channel_id
            }
            print(data)
            await KookBot.call_api(main_inst_bot, 'channel/move-user', **data)
就解决了
